### ISSUE TITLE
Playing on a filed that just got captured causes the game to restart, thus forcing a sript re-injection manually

### ISSUE THREAD

**Issue by CaramelloDido** [meepen/salien-bot#11]
Since the script prioritizes a square with high progress, it can happen that sometimes you are playing it, and said square gets captured mid-game, if that happens the game cant "report the score" and a "restart the game" pops up.

**Comment by LeO-Fr** [comment]
yes and also randomly, if we go this restqrt error we have to click on play manually and reinject the code to, is it possible to made it fully automatic?

**Comment by Z4jac** [comment]
I think it is but you will need to add line to script that wil accept game restart and Tampermonkey or something else to inject script after refresh. I'm not a programer so can't realy help :/

**Comment by ehea617** [comment]
This could be fixed if it was converted into a Greasemonkey script.

**Comment by meepen** [comment]
Added grease/tampermonkey support!
