### ISSUE TITLE
Headless not even finding a zone (saliens crashed not this i guess)

### ISSUE THREAD

**Issue by Tosh-k1** [meepen/salien-bot#110]
the game crashed, bad timing, sry

**Comment by EoD** [comment]
@Tosh-k1 any reason you closed this?

**Comment by Tosh-k1** [comment]
because i realized that the saliens game had crashed which was most likely causing this script to not find a zone rather than a bug in the script. 


didn't want to waste anyone times so i closed it as i couldn't see a way to delete it
