### ISSUE TITLE
Properly convert to *monkey script

### ISSUE THREAD

**Issue by Evanito** [meepen/salien-bot#12]
needs to be named `*.user.js` for Tampermonkey etc. to recognize it as a script for it.
Also setting up updating tags for it would be 💯 

```
// @downloadURL  https://raw.githubusercontent.com/meepen/salien-bot/master/salien-bot.user.js
// @updateURL    https://raw.githubusercontent.com/meepen/salien-bot/master/salien-bot.user.js
```

**Comment by meepen** [comment]
ah thanks

**Comment by fredd727** [comment]
im almost sure you'll also have to
 ``@include https://steamcommunity.com/saliengame/play/ @match https://steamcommunity.com/saliengame/play/``
or something like that

**Comment by meepen** [comment]
what does `@include` do?

**Comment by Evanito** [comment]
https://tampermonkey.net/documentation.php

Define pages where it should run. You can use `*://steam...` to support both http and https

**Comment by Evanito** [comment]
Remember to increment `@version` to push the new version to the autoupdater :)

**Comment by JourneyOver** [comment]
Also either should change the name to either `salien-bot.user.js` or change the `downloadURL` and `updateURL` to `https://raw.githubusercontent.com/meepen/salien-bot/master/index.user.js` instead.

**Comment by meepen** [comment]
All good now?

**Comment by JourneyOver** [comment]
Yep that looks good, now if I could actually get it to run without it throwing the error I mentioned in #16 it'd be great >.<
