### ISSUE TITLE
ajax_object.nosucc();

### ISSUE THREAD

**Issue by Adenser** [meepen/salien-bot#123]
After 3-4 hours of working this error showed 
![image](https://user-images.githubusercontent.com/39248856/41820517-62a81c30-77d3-11e8-94ed-84cb9cddb48c.png)

**Comment by EoD** [comment]
@Adenser are you using the current version  "1.2.2" of the script? There have been quite some fixes.

**Comment by Adenser** [comment]
nvm, trying to be up to date is very hard ;-;

**Comment by csis0247** [comment]
Just FYI, I experienced the same bug on headless version "1.0.1" and "1.1.1" for about 3-4 times in the past 12 hours. Granted, they are much older versions of the script. I am guessing it occurs whenever a planet is being conquered. So we have about 4 hours to go to see if the bug has truly been fixed when Glory Days Planet III is conquered.
