### ISSUE TITLE
Windows setup/start script for headless

### ISSUE THREAD

**Issue by MainFighter** [meepen/salien-bot#130]
I don't know if anyone would be interested in this but I made a setup/start script for my friends and I so we can easily farm multiple accounts (works with one). Makes it fairly simple to get the headless version up and running.

https://github.com/MainFighter/salien-bot/tree/winstartscript

Sorry if I shouldn't be posting it here, you can remove it if you like.

**Comment by darkl1ch** [comment]
`@echo off
title Salien-bot starter
echo "Steam Summer Sale (Salien)"
echo "------------------------------------"

set botpath="c:\path_to_bot_folder"
set botfoldername="salien-bot-master"

cd %botpath%/%botfoldername%

node headless

pause`

why not just use this instead? :o main page of bot has the instructions, the above code saved into a file like bot.bat can start up your bot, you only have to change two things (or 1).. the bot folders path.
easy..

**Comment by darkl1ch** [comment]
yes, but not all of us having git and extra commands. like me, i just installed nodejs just cuz of this.
but yeah, dont get me wrong, thx for the commitment, thx for writing such, but in my opinion its too much thing to just install. :)
and btw i have checked your code :)
auto update is a nice feature though, so thats ++.

**Comment by meepen** [comment]
i can't take your code myself, but if you'd like to make a pr others and i can decide if it would be a good addition.
