### ISSUE TITLE
[Suggestion] Create or Support DISCOVERY QUEUE skipper

### ISSUE THREAD

**Issue by aompqn** [meepen/salien-bot#137]
Cant find good and fast skipper. Have now "SteamDiscoveryQueueAutoSkipper" but it have troubles: https://github.com/PotcFdk/SteamDiscoveryQueueAutoSkipper/issues/5

Can you support another or create yours? Thank you!a

Better add some page-cut options like cut game-streams from page.

**Comment by TryHardHusky** [comment]
xPaw already has a fantastic queue script.  
  
https://gist.github.com/xPaw/73f8ae2031b4e528abf7

**Comment by meepen** [comment]
this is out of scope for this project, you can use the alternatives above if you'd like.
