### ISSUE TITLE
Can't run it on Raspberry Pi B+

### ISSUE THREAD

**Issue by SuicidalcookieS** [meepen/salien-bot#138]
I have installed Node on the raspberry pi b+ and downloaded the newest version of the headless bot and when i try to node headless it won't do anything.

What do i have to do, i'm kinda new to linux. and raspberry pi

**Comment by elamperti** [comment]
@SuicidalcookieS have you ran `npm install`? Have you set the Steam token in `gettoken.json`?

I'm not familiar with the code but mentioning your node version (`node --version`) may be helpful as well.

**Comment by meepen** [comment]
we need more info to help you. as others have said it seems to work fine on that platform as well.

**Comment by SuicidalcookieS** [comment]
I have a clean installation of raspbian and have updated it. After that i have installed node with `sudo apt-get install node -y` and it installed the latest version of node on my PI, now if i type in `node --version` it doesn't do anything / it doesn't show anything it like freezes for 3 - 5 second and goes back to the `pi@raspberrypi :~` so what am i doing wrong and yeas i have set the steam token in the gettoken.json file.
![2018-06-28_10-39-34](https://user-images.githubusercontent.com/40127960/42023219-9af28bea-7abf-11e8-951a-cedce2dd04ad.png)
