### ISSUE TITLE
Meepen could you look at my old [ Closed ] issue about the raspberry pi? [ DELETE THIS LATER ]

### ISSUE THREAD

**Issue by SuicidalcookieS** [meepen/salien-bot#139]
https://github.com/meepen/salien-bot/issues/138

**Comment by callmenemo491** [comment]
maybe useful for you:
http://thisdavej.com/beginners-guide-to-installing-node-js-on-a-raspberry-pi/

**Comment by SuicidalcookieS** [comment]
![putty_2018-06-28_15-19-36](https://user-images.githubusercontent.com/40127960/42036740-b2912aaa-7ae6-11e8-8f3c-488d0b297fb9.png)

**Comment by SuicidalcookieS** [comment]
@callmenemo491 thanks for the link to the Node JS tutorial for the Pi it helped but now i get this problem ( See screenshot above ).

**Comment by elamperti** [comment]
@SuicidalcookieS now that node is working run `npm install` again, then you should be good to run `node headless`.

In the future stick to the issue you already opened, don't create a new one unless it's unrelated to the previous problem; it's "bad etiquette". Cheers! :smiley:

**Comment by SuicidalcookieS** [comment]
@elamperti Thank you so much i have got it running and working on all six of my accounts, again thank you so much.
