### ISSUE TITLE
Next Level up time wrong

### ISSUE THREAD

**Issue by danielkp1234** [meepen/salien-bot#141]
So it says next level up is 18:00 but its 18:13 and it still says 18:00
![screenshot_2](https://user-images.githubusercontent.com/19412591/42046855-157f7384-7aff-11e8-81a8-b676f17c562e.png)
Just wanted to let you know

**Comment by darkl1ch** [comment]
29jun man.. :) not 28jun.

**Comment by danielkp1234** [comment]
Oh sorry
