### ISSUE TITLE
Script not working at all since 20 minutes (the Steam time)

### ISSUE THREAD

**Issue by LeO-Fr** [meepen/salien-bot#145]
All in the title, the steam store is refreshing every day (20 mins ago), and since the script it's not working (it's running but not playing at all)

**Comment by darkl1ch** [comment]
so i presume this is for the userscript.
have you tried to use the headless mode? its way better than the tappermoneky - userscript version.
i recommend you to stop the browser script, install nodejs and use the headless version.
the setup is simple and easy, you will like it more than the other one. :)

**Comment by LeO-Fr** [comment]
no it's for the headless mode.
I was using the headless mode since it's available, and today it's not farming at all

**Comment by darkl1ch** [comment]
well. its probably because of the token. you generate a new one. :)

**Comment by ntfshard** [comment]
I had some issues on boss levels on line "enemies.forEach((enemy) =>"

**Comment by callmenemo491** [comment]
steam changed something, so now the script does not work ;(
**TypeError: enemies is undefined**

Dusty Planet zone 20 (8, 1) progress: 0.0000034482106912037125 difficulty: 3    userscript.html:186:9
join to zone 20                 userscript.html:124:13
20                              userscript.html:137:9
TypeError: enemies is undefined
process                         moz-extension://5b8a5701-db57-4a03-a9c3-16e596fd1506/userscript.html:287:9
ticker                          moz-extension://5b8a5701-db57-4a03-a9c3-16e596fd1506/userscript.html:460:13
[120]</i</t.prototype.emit      https://steamcommunity-a.akamaihd.net/public/javascript/saliengame/pixi/pixi.min.js:16:18820
[119]</c</t.prototype.update    https://steamcommunity-a.akamaihd.net/public/javascript/saliengame/pixi/pixi.min.js:16:17776
t/this._tick                    https://steamcommunity-a.akamaihd.net/public/javascript/saliengame/pixi/pixi.min.js:16:15959

**Comment by callmenemo491** [comment]
updated the script to:  version      26
cheers @meepen!

**Comment by meepen** [comment]
in the future, look for other issues that relate to your errors or create new ones if you can't find any! 👍
