### ISSUE TITLE
ReportBossDamage error handling

### ISSUE THREAD

**Issue by sheep** [meepen/salien-bot#162]
Hi,

https://github.com/meepen/salien-bot/blob/3e863fed13f1382ff7211d01019549498b1a6592/headless/network.js#L246

That should be:
`        error( null, request.getResponseHeader( 'x-eresult' ) );`
otherwise, the ReportBossDamage state in the main file cann't handle the eresult==11.

**Comment by ahakola** [comment]
You could do pull request on this for @meepen to merge?

**Comment by sheep** [comment]
I guess the main code don't care anymore. So that issue is fixed :-).
