### ISSUE TITLE
Script wait for FIGHT to be pressed for Boss Battle

### ISSUE THREAD

**Issue by callmenemo491** [meepen/salien-bot#166]
when boss battle starts,  you need to wait for the "FIGHT" button/text to appear.
once you click "FIGHT" then the battle begins.
Am running: index.user.js (version 29)

![bossbattle_stopped_at_fight](https://user-images.githubusercontent.com/13878580/42132966-ca910364-7d5c-11e8-969c-06b5cc7b8d63.JPG)

**Comment by callmenemo491** [comment]
Am running: index.user.js (version 29)

**Comment by meepen** [comment]
`gGame.m_State.m_IntroScreen.children` should have an object that has `buttonMode: true` with a child that has `["_text"]` in it, we should click that child and it should be fine.

**Comment by callmenemo491** [comment]
PR #170, to support boss "fight" button press
