### ISSUE TITLE
Headless script stops on boss fight 

### ISSUE THREAD

**Issue by dakkarino** [meepen/salien-bot#168]
Most of the times on the boss fight Boss HP and Boss EXP stop, with only the time changing. In this case the easy boss fight has been going on for well over two hours. This happened for me on the last two days. Last boss fight was two days ago, if I recall correctly.

C:\downloads\programs\steam\salien-bot-master>node headless -l
Playing as:       dakkarino
Running for:      3h 9m 39s
Current level:    16 (9142570 / 9600000)
Exp since start:  48000
Estimated exp/hr: 18782
Current planet:   Planet of Jumpless Platformers [80.126%] (id 39)
Current zone:     (8, 3) BOSS easy [51.340%] (id: 44)
Boss HP:          20998426 / 40000000 [52.50%]
Boss EXP:         385000

[log_201807011640.txt](https://github.com/meepen/salien-bot/files/2152824/log_201807011640.txt)

**Comment by callmenemo491** [comment]
the boss fights are working now... i had one earlier today.

**Comment by meepen** [comment]
what version are you running?

**Comment by dakkarino** [comment]
// @version      27

**Comment by dakkarino** [comment]
Updated to the latest 29 just now, I will keep you posted on the issue.

**Comment by meepen** [comment]
that's not headless version - that's in package.json
but yeah that should fix it
