### ISSUE TITLE
How can I stop it?

### ISSUE THREAD

**Issue by giv13** [meepen/salien-bot#180]
Sorry for my stupid question. But how can I stop it? I'm using Headless mode. And I installed it on my hosting. When I reached level 25, I stopped it with Ctrl+C and deleted the files from the hosting. But it continues working. I see that my rank is growing, and I get 3 cards every day.

**Comment by meepen** [comment]
it stops when you hit ctrl+c, if it doesn't then you are running the bot still or running another bot lol

**Comment by giv13** [comment]
I swear it isn't so. I no longer have any copies of bots. 100%

**Comment by meepen** [comment]
not sure what to tell you, the script has to be running to work.

**Comment by meepen** [comment]
if you want to invalidate your token and have the bot stop working for sure, you can just change your steam password; that might mess with trading and stuff though.

**Comment by giv13** [comment]
Tell me please, if I didn't stop the bot by pressing Ctrl+C and just deleted the files. Can the bot continue to work because of this? Big thanks for help.
