### ISSUE TITLE
This is not a bug, but a question.

### ISSUE THREAD

**Issue by KrisZane** [meepen/salien-bot#185]
First of all, so sorry for posting this here, but I couldn't find anywhere else to ask this (or any useful Google results). I am quite intrigued with the context value in the constructor, I haven't seen that used before in userscripts and I can't seem to find out where it comes from. Could you possibly give a short description of where it comes from and what the object references? :P

**Comment by meepen** [comment]
at the bottom, it calls the function we create with the context argument with `window`
