### ISSUE TITLE
Infinite page reloading when not inside a planet

### ISSUE THREAD

**Issue by thomas-ashcraft** [meepen/salien-bot#23]
Firefox 60.0.2
Tampermonkey 4.7.5788
Absolutely no in-game actions before script installing (dont know if it matters).

Install script.
Go to https://steamcommunity.com/saliengame/play/

The game starts loading like it was "Play" button clicked, and simultaneously the whole page in browser is reloading.

**Comment by bb10** [comment]
Same here, on both firefox 61 and opera 53.

**Comment by Js41637** [comment]
Opera as well? Opera is basically Chrome, does it not happen on Chrome?

**Comment by wubstepper** [comment]
It does happen on Chrome confirmed

**Comment by meepen** [comment]
this might be because you haven't selected a planet. let me check

**Comment by meepen** [comment]
100% that issue. right now im trying to get firefox support but for now you can just select a planet with the script off.

**Comment by Js41637** [comment]
Script works fine for me in Firefox with a planet selected.

**Comment by bb10** [comment]
Confirmed, needs planet selected first. thanks :) 👍

**Comment by wubstepper** [comment]
To get it to work on Chrome on tapermonkey↓
>Turn off script
>Reload page
>Play
>Select a planet
>Turn on the script
>Reload the page
>...Hope

**Comment by TehDmitry** [comment]
is #13 fix the issue?

**Comment by meepen** [comment]
should be fixed
