### ISSUE TITLE
How to find specific ID of tile

### ISSUE THREAD

**Issue by Simzy** [meepen/salien-bot#27]
Is there a way i can find the ID of a specific tile and then be able to repeatedly farm that tile?

**Comment by TehDmitry** [comment]
You can use zone Index instead Id 
`gGame.m_State.m_Grid.m_Tiles`

also zone index print in console:
Pirates Planet **zone 83 (11, 6)** progress: 0.1833868771791458 difficulty: 2

**Comment by Simzy** [comment]
okay found the tile i wanted simple enough but how can i make the script go back to that tile instead of going to other random ones

**Comment by TehDmitry** [comment]
for quick fix add
`return zoneIndex;`

after
`const GetBestZone = function GetBestZone() {`

in result you should get something like this:
```
const GetBestZone = function GetBestZone() {
    return 15;
    let bestZoneIdx;

```
