### ISSUE TITLE
Chosen planet is ignored on refresh

### ISSUE THREAD

**Issue by smaus** [meepen/salien-bot#30]
When the game gets an error and has to restart, or if you manually refresh the page, or otherwise return to the title screen, the script chooses a planet on its own (in this case, the Pirate Planet).

However, if I disable Tampermonkey, then refresh and click Play manually, the game automatically loads my chosen planet properly (eg. Dark Humor Planet). Enabling the script at this point starts a battle on the proper planet and all is well.

I'm not even sure how this happens, since there isn't even an opportunity for me to choose the planet manually unless I specifically quit out of the planet I'm already on first. The script shouldn't be adding extraneous steps.

**Comment by meepen** [comment]
it should be fixed if you update it all!
