### ISSUE TITLE
doesn't auto go to the next game

### ISSUE THREAD

**Issue by Kapleo** [meepen/salien-bot#39]
I'm running it on chrome
it just finishes the game I'm on and I have to manually go to the next game

**Comment by meepen** [comment]
i'm going to be redoing some state changes soon which will have cooldowns and stuff, then i'd like you to try again

**Comment by VADemon** [comment]
200 https://community.steam-api.com/ITerritoryControlMinigameService/ReportScore/v0001/
`{"response":{"old_score":"701235","old_level":9,"new_score":"702405","new_level":9,"next_level_score":"1200000"}}`
200 https://community.steam-api.com/ITerritoryControlMinigameService/GetPlayerInfo/v0001/

(not headless version) After the game ends there's only "Reporting Score to Salien High Command" and no button to continue.
Looks like a Steam issue, but the game is stuck at End screen indefinitely now.

**Comment by meepen** [comment]
When a planet ends, the whole game lags. If you afk on it, it will be back to normal soon.
