### ISSUE TITLE
Not clicking 

### ISSUE THREAD

**Issue by TruthFire** [meepen/salien-bot#44]
Don't know why, but it's not clicking on enemys,just shooting with "1" button. what could be wrong?

**Comment by iosoft** [comment]
I agree.
It should SHOOT non-stop. All I have to do is move the mouse around.

**Comment by Js41637** [comment]
I think it is clicking, you should see the turret move sometimes, does it really matter though as long as everything is dying?

**Comment by TruthFire** [comment]
Could be, turret just moves by few pixels forward and backward

**Comment by iosoft** [comment]
Oh! Now I noticed :P

**Comment by meepen** [comment]
It does shoot, it just doesn't show the animation

**Comment by iosoft** [comment]
Thats why I got confused.

Its the BEST bot script.
Keep it up :)
