### ISSUE TITLE
Game loop crashes after some game

### ISSUE THREAD

**Issue by sohich** [meepen/salien-bot#48]
Hello Sir! Sometimes game loop interrupts after the  finish of a round with this error:
`Uncaught TypeError: Cannot read property 'click' of undefined
at setTimeout (<anonymous>:362:55)`
Game indicates an error, game reloads and I have to insert the script into the console again.

**Comment by stumpylog** [comment]
I'm also seeing this.  Seems to happen after a couple of games.  I'm pasting the script into the console, using Chrome, if that helps

**Comment by meepen** [comment]
work any better in latest version?

**Comment by stumpylog** [comment]
Yes, it seems to be working better for me.  I also changed over to the TamperMonkey, so I'm not sure which thing fixed it for me

**Comment by sohich** [comment]
Latest version doesn't work for me at all with error:
`VM4909:1 Uncaught SyntaxError: Identifier 'MAX_LEVEL' has already been declared
    at <anonymous>:1:1`

**Comment by meepen** [comment]
fixed that
