### ISSUE TITLE
Script doesn't seem to submit the score

### ISSUE THREAD

**Issue by asasantana** [meepen/salien-bot#49]
I've been running the script for a while with tampermonkey but it seems like each time the level is completed the script refreshes before submitting the score, so it never counts the game. I've left it for a couple hours and it didn't go through a single game since my level is the same. Any solutions to this?

**Comment by meepen** [comment]
so with the headless version i've been working on i can confirm it sometimes doesn't submit score, need to look at api scores

**Comment by meepen** [comment]
#28
