### ISSUE TITLE
Fail, no socre after that

### ISSUE THREAD

**Issue by Celestin6669** [meepen/salien-bot#50]
After game it says "failed to load your score" or something like that, so i got no xp and didnt get progress for that "tile" and it restarts after that

**Comment by realzerojimmy** [comment]
Me too, my game finish and back to the map but no xp :/

**Comment by meepen** [comment]
You do get exp, it's just delayed because of how we log it.

**Comment by Celestin6669** [comment]
If it delayd, why i didnt got xp for 6 games that i played on high risk tiles?

**Comment by PredatorIWD** [comment]
After 20h of play on the same planet, using always the latest version of the script and chrome, I gained only a few thousand XP during only specific times at the start and after that absolutely 0 for the next 16-18h... Switching to other scripts started giving me XP right away. There seemed to always be a steam error at the end of most, if not every game which required a browser reload.
