### ISSUE TITLE
randomly stops working after a few  games

### ISSUE THREAD

**Issue by avasn** [meepen/salien-bot#53]
gets stuck at the main menu and sometimes in title select

**Comment by meepen** [comment]
logs?

**Comment by avasn** [comment]
it seems that it's stopped auto pressing start on the main menu 
the only logs i get from loading the main menu is
Source map error: request failed with status 404
Resource URL: https://steamcommunity-a.akamaihd.net/public/javascript/saliengame/pixi/pixi.min.js?v=.tDHAybGykI1O
Source Map URL: pixi.min.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: https://steamcommunity-a.akamaihd.net/public/javascript/saliengame/pixi/pixi-spine.js?v=.7OsC6yYlmcju
Source Map URL: pixi-spine.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: https://steamcommunity-a.akamaihd.net/public/javascript/saliengame/pixi/pixi-filters.js?v=.0zUgeJIQqNXu
Source Map URL: pixi-filters.js.map[Learn More]
Source map error: request failed with status 404
Resource URL: https://steamcommunity-a.akamaihd.net/public/javascript/saliengame/pixi/pixi-sound.js?v=.x9Q08vlRNyLh
Source Map URL: pixi-sound.js.map[Learn More]
Error: WebGL warning: drawElements: This operation requires zeroing texture data. This is slow.



pressing start continues normal actions

**Comment by jdydsco** [comment]
I have noticed the same thing recently. Twice it's stopped on the main screen where you have to press start, and pressing start will make it work again.

**Comment by DeathCoreLeo** [comment]
I have the same bug, in chrome (67.0.3396.87 x64 \ Tampermonkey
4.6) - script not push button "Press start"
and in Opera (53.0.2907.106 \ Tamper 4.2.5291) - all fine work

if I do it manualy it work until next while game not enter again at start screen
before 1 hour ago all working fine =)

**Comment by jdydsco** [comment]
![screenshot_2018-06-22_18-49-30](https://user-images.githubusercontent.com/40505249/41802199-a67ed388-766e-11e8-8355-ff989beb3e1f.png)

Just failed again; it went back to the tile screen this time and all of the tiles appeared to have 0 progress (new planet or something?). Kept repeating the same thing in the console screenshot. I clicked one of the empty tiles and it started working again.

**Comment by darkl1ch** [comment]
i have the same issue.. it stops after a few rounds and i have to click on play again to just run the "bot" again..
