### ISSUE TITLE
Headless hangs when no planet is selected

### ISSUE THREAD

**Issue by EoD** [meepen/salien-bot#56]
If the player presses "leave planet" and the uses the headless NodeJS bot, the bot seems to hang and never start. 

Is it meant to select the planet with the highest count of "High" thread tiles?

**Comment by meepen** [comment]
whoops didn't mean to close this

**Comment by anditsung** [comment]
i think no hangs. but the bot cannot continue after the planet is finish

**Comment by meepen** [comment]
should be fixed?

**Comment by EoD** [comment]
Bot does not get stuck anymore when no planet is selected
