### ISSUE TITLE
Uncaught SyntaxError: Unexpected token const

### ISSUE THREAD

**Issue by Tetrisson** [meepen/salien-bot#6]
![1](https://user-images.githubusercontent.com/38470813/41745285-ddc9f1f6-75bf-11e8-9dc2-b4233b975d90.jpg)

What is the problem?

**Comment by meepen** [comment]
This should be fixed in an update, was it not?

**Comment by Tetrisson** [comment]
Oh, sorry, I'm not very smart.

**Comment by meepen** [comment]
No problem, I don't blame you either since it's being updated so often with some broken commits.
