### ISSUE TITLE
Not gaining XP

### ISSUE THREAD

**Issue by Archen55** [meepen/salien-bot#63]
Any reason why some users are not getting XP at all after running the script for some time?

**Comment by anditsung** [comment]
what version are you running?

**Comment by Archen55** [comment]
18

**Comment by Archen55** [comment]
**Update:** so, I'm on ver. 24 and it's still stuck. I was forever stuck on 75045 XP, and there was no way to make the script pass over it. I had to play myself to make it go up, and the script simply seems to not be working properly, as I'm still not getting XP.

Would you kindly investigate?

**Comment by meepen** [comment]
Can you give your whole setup to me @Archen55 ? browser, userscript manager, version

**Comment by callmenemo491** [comment]
i believe what is happening, is that the script is choosing the tile which is like 99.9999% completed, and whilst you are playing that tile, the tile becomes 100%, so when you complete it, the game rejects your XP earned, and therefore it is not 'saved'.
perhaps, it is better to make the script,  filter out tiles which are like 99% completed, or something like that.

**Comment by callmenemo491** [comment]
looking at console debug:,  confirms my suspicions... progress is above 95% (0.96),
my XP is not saved.
but when the script picked a tile which was 0.5% completed, the score was saved.

```
Mythology Planet zone 73 (1, 6) progress: 0.9648227691650391 difficulty: 3
join to zone 73
73

Arguments { … }
Navigated to https://steamcommunity.com/saliengame/play

Mythology Planet zone 36 (0, 3) progress: 0.005151200108230114 difficulty: 2
join to zone 36
36

Server reported level 7 (156810 / 180000)
continued!
Mythology Planet zone 80 (8, 6) progress: 0.005579200107604265 difficulty: 2
join to zone 80
80
```

**Comment by callmenemo491** [comment]
am not sure on the javascript code, to make the script ignore tiles which are like say 95% completed.

**Comment by callmenemo491** [comment]
FireFox 60.0.2 x64, Tampermonkey 4.7.5788 + Script v24

**Comment by memehammad** [comment]
i'm using the headless mode and i'm also not gaining any xp

**Comment by VanackSabbadium** [comment]
The "normal" script works good, but the headless one doesn't make me gain any xp points also.

Google Chrome 66.0.3359.170 + Tampermonkey 4.6 + Script v24

**Comment by davidphood** [comment]
I had issues with both scripts.

I was able to get the "normal" script to reward xp again by changing my character's customisation options back to the ones seen when the script is running (which for some reason were the same options as when I first ran the script - except for the body type which was changing)

**Comment by memehammad** [comment]
the game seems to restart too quickly, its already reloading while its still uploading my score

**Comment by MainFighter** [comment]
yeah headless isn't working for me either, just not gaining exp

**Comment by davidphood** [comment]
It could actually be one of those errors at, which forces it to reload.

**Comment by VanackSabbadium** [comment]
@Scyoni it doesn't work for me. I replaced it in index.user.js, is that right?

**Comment by memehammad** [comment]
this only works on the web version

**Comment by Scyoni** [comment]
Yes, but it will only fix the user script version not the headless one. If it's still redirecting before your score is uploaded you can increase the delay by changing the 5000 and 6000 to a higher number (just make sure whatever you replace 5000 with, you replace 6000 with something 1000 higher).

**Comment by VanackSabbadium** [comment]
@Scyoni oh, i understand. Well, my user script version works fine, i need a fix for the headless version, since i'd like to close Google Chrome to free some RAM. I'll wait for a fix by @meepen :)

**Comment by callmenemo491** [comment]
tested the solution provided by @Scyoni, and it works for me very well.
have done a pull request so its in the final solution

**Comment by meepen** [comment]
still happening?
