### ISSUE TITLE
Get Error "TypeError: SERVER is null"

### ISSUE THREAD

**Issue by callmenemo491** [meepen/salien-bot#64]
Running version: v24  (normal mode  -> i.e., non-headless), ViolentMonkey
Script stopped working.

See in the FireFox developer console (error):

```
Error running script: Saliens bot
TypeError: SERVER is null
SERVER is null
```

**Comment by anditsung** [comment]
trying using tampermonkey.
i dont have this issue

**Comment by callmenemo491** [comment]
removed ViolentMonkey & installed tampermonkey. all is ok.
thanks @anditsung !
