### ISSUE TITLE
PSA Google Chrome Tampermonkey, in order to update the script properly, uninstall it fully then reinstall it

### ISSUE THREAD

**Issue by TotalLegitREMIX** [meepen/salien-bot#66]
Don't know the cause, but it wasn't changing anything until I fully uninstalled it and reinstalled it. Just posting this so people will see before leaving an issue report.

Also thanks Meepen, for keep this up to date so fast and making it so well :)

**Comment by 13xforever** [comment]
you need to refresh the steam page for the new script to run

**Comment by meepen** [comment]
you just need to revisit the download page or hit update.
