### ISSUE TITLE
commend

### ISSUE THREAD

**Issue by WIN4ig** [meepen/salien-bot#67]
Please make a choice of planets manually. A choice of level hard as "if there is hard->do hard,else if there is medium do medium,else low"
And organize the attack, as in this script, and then the drawing of each model loads my old PC.
https://pastebin.com/1LkRyKVc

**Comment by callmenemo491** [comment]
perhaps you can do a pull request to update the logic.

**Comment by WIN4ig** [comment]
My trouble in this I do not know javascript absolutely.

**Comment by meepen** [comment]
i'm not sure what you actually want me to do here; and which version are you talking about?
