### ISSUE TITLE
Bot "overshoots" Salien Special skill

### ISSUE THREAD

**Issue by EoD** [meepen/salien-bot#72]
When you are starting anew, the bot performs very badly as the default skill `1` does overshoot enemies almost all the time.

This is especially noticeable when you are on hard and enemies are walking very fast it barely hits them.

**Comment by TehDmitry** [comment]
confirm.
I try to fix it in my fork before pullrequest

**Comment by EoD** [comment]
@TehDmitry I have a fix, no worries
