### ISSUE TITLE
Can't get exp use headless

### ISSUE THREAD

**Issue by gyq180** [meepen/salien-bot#75]
![image](https://user-images.githubusercontent.com/20734242/41809767-b45664dc-7725-11e8-9182-17c3d4e50b3a.png)

My version is the latest.

**Comment by nudpad** [comment]
Been at this for like an hour, switched back to the browser version, seems to be working for now, change planets, care for planets.

Mine seems its waiting for the round to end to start the game, but it just keeps looping, no exp gaining

**Comment by Psychh** [comment]
ui upgrade bugged it use https://github.com/meepen/salien-bot/tree/45a11c8469ca0fc7d1f9b6d6e0404fb9265a33eb in the mean time
or wait

**Comment by EoD** [comment]
@Psychh do you know which commit is the failing one? 326cc8f1f014687539139a28fa45a32a05071734?

Can you point out what exactly broke?

**Comment by BradyThe** [comment]
https://github.com/meepen/salien-bot/commit/3b3a1eb6b756715d6cf50a06c1ed3cd20538a38a broke it. After downgrading to https://github.com/meepen/salien-bot/commit/8cb3047c3863bdee2bc356484afa179aa78d8604#diff-0047580b90a4de60c0c8185a1765ed33 it again works flawlessly.

Something tells me that it should be easy to point out the flaw, but I am no programmer and not familiar with the whole script at all.

**Comment by Daffehh** [comment]
It seems that the score is being reported as waiting for a result? I don't exactly have a great grasp on lambdas or async, but it seems the score is just not being reported properly.

**Comment by meepen** [comment]
sorry, i accidentally pushed code i shouldn't have and went to bed. i'm looking for people to add to contributors currently to stop this from happening again.

**Comment by nudpad** [comment]
thank you meepen for incredible work!!!

**Comment by robme** [comment]
It still doesn't give any XP in latest version.
