### ISSUE TITLE
Cant get any Xp 

### ISSUE THREAD

**Issue by tiago199988** [meepen/salien-bot#81]
I cant get any xp i got the cards but no xp 
https://media.discordapp.net/attachments/327531611434516482/460065409484193822/unknown.png

**Comment by callmenemo491** [comment]
duplicate of: #63, #74

**Comment by tiago199988** [comment]
yes i know its duplicate but why its hapening ???

**Comment by callmenemo491** [comment]
better for you to ask your question (why it happen) into ticket #75,
and close this one.
