### ISSUE TITLE
Best square isn't always one with most experience

### ISSUE THREAD

**Issue by 0wnMe0rDie** [meepen/salien-bot#9]
You should change the selection to not be one with highest progress but start with high difficulty maximum progress and work your way down. That way, people can maximize the experience gain.

**Comment by thejko** [comment]
If possible, I believe it should prioritize rejoining the same square you selected manually at the start (for groups attempting to synchronize efforts) and then default to what you suggested above.

**Comment by meepen** [comment]
How about boss > highest difficulty > progress?

**Comment by thejko** [comment]
That makes the most sense for leveling.

**Comment by meepen** [comment]
level 9 is the highest level correct? I can probably make it go to level 9 before going back to the old one.

**Comment by vaibhavhrt** [comment]
Yeah, in fact the script should select the square with least progress so we always get exp.

**Comment by meepen** [comment]
@vaibhavhrt sounds good, will do that

**Comment by vaibhavhrt** [comment]
Thanks @meepen it works great now.
