### ISSUE TITLE
ERROR! :C HELP PLS.

### ISSUE THREAD

**Issue by marz0r** [meepen/salien-bot#91]
![image](https://user-images.githubusercontent.com/40527734/41813488-c9a251f6-773f-11e8-8031-e192dda40ae1.png)

**Comment by Daffehh** [comment]
Weird, it says there's no file, but there is a file there, huh

**Comment by Daffehh** [comment]
@marz0r could you provide the full log at the local it said its at?

**Comment by marz0r** [comment]
D:\salien-bot-master

**Comment by meepen** [comment]
you appear to have extensions disabled in the explorer, and you see `gettoken.json`, the real file name is going to be `gettoken.json.json`. Rename what you see as `gettoken` and it should work

**Comment by marz0r** [comment]
Thanks man!
