### ISSUE TITLE
[Docker] Official Docker Hub repository

### ISSUE THREAD

**Issue by tokkenno** [meepen/salien-bot#94]
Hello @meepen. Can you create an account on Docker Hub and create an "official" repository?

The repository that I created (https://hub.docker.com/r/reimashi/salien-bot) call to my fork on https://github.com/TokkennoForks/salien-bot, but the commit trigger for auto update isn't working automatically for some reason... and I can't create a repository on Docker Hub linked directly to your Github repo by his security policies.

It's to easy, create an account, select the "Create automated build" option and link the github account for access the repository.

<img width="131" alt="screenshot_1" src="https://user-images.githubusercontent.com/5956659/41813924-469df444-7740-11e8-8bb6-ac76d2fcab42.png">

The image will be created automaticaly from the git sources.

**Comment by meepen** [comment]
not sure if this is how you do it? <https://hub.docker.com/r/meepen/salien-bot/>

**Comment by tokkenno** [comment]
Yes, works well.
